### PR TITLE
Enemy manager implementation + spawner refactor

### PR DESCRIPTION
**Pull request by gdodge0**
Objectives:

**1. Be able to restrict the area of spawning of the enemies**
    -> Accomplished via checking if the attempted spawn location is within a safe_zone (Rect2i)
    -> Spawning will be aborted if the chosen location is within a forbidden area.
**2. De-spawning is consistent and possible**
    -> Enemies are de-spawned once they exceed 2000 units distance from the player.
    -> The code runs every physics frame, but we could reduce it to every second or so. It doesn't have a huge impact on performance either way.
**3. Spawn cap**
    -> Added a dict "enemyData" to EnemyManager which contains metadata about how to spawn enemies, at what proportion, and the maximum amount to spawn.
    -> set to 10 for greenSlime
**4. Different spawn rates for different enemies**
    -> enemyData contains an entry "spawn_rate" which defines how often a given entity should spawn relative to others. It can be incremented or decremented in 10ths. E.g. greenSlime = 1.5 yellowSlime = 0.7

**Perhaps even different areas of the world?**
    -> I'm planning on adding this in the future once we get more enemies in the game. Each enemy will have a spawn_type that defines where it can be found and with what frequency. We could also have different tables for spawnrates depending on player coordinates.

### CODE REVIEW

**Comment by gavindg** [comment]
There's currently an error that pops up if you kill an enemy; the function `is_out_of_range` will try to get the global pos of a freed enemy on line 41. a few ways you might be able to fix this:
1. check if the enemy is already freed before calling is_out_of_range on it on line 61, and if so just remove it from the dict
2. remove the enemy from the dict when it dies (not sure which file that's handled in though, and its probably better to keep that behavior within EnemyManager)

other than that, beastly PR. Really like the way you structured the spawner w the enemy dict & IDs, very easy to work with when we have more enemies later. lmk when you fix the bug & I'll merge it

**Comment by gdodge0** [comment]
> There's currently an error that pops up if you kill an enemy; the function `is_out_of_range` will try to get the global pos of a freed enemy on line 41. a few ways you might be able to fix this:
> 
>     1. check if the enemy is already freed before calling is_out_of_range on it on line 61, and if so just remove it from the dict
> 
>     2. remove the enemy from the dict when it dies (not sure which file that's handled in though, and its probably better to keep that behavior within EnemyManager)
> 
> 
> other than that, beastly PR. Really like the way you structured the spawner w the enemy dict & IDs, very easy to work with when we have more enemies later. lmk when you fix the bug & I'll merge it

I see, didn't know damage was implemented yet. I'll find out where its at and fix it before our meeting.

**Comment by gdodge0** [comment]
There's a third solution and that is to move enemy damage into EnemyManager and call manager.damage_enemy(amount) instead of however its being handled atm. I think that is my preferred solution.

**Comment by gdodge0** [comment]
@gavindg Fixed, here are the changes:

globals.gd
 -> add manager to globals
enemy.gd
-> On death, call Global.manager.despawn instead of directly queue_free()-ing the enemy

**Pull request merged**
